import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Eye, ExternalLink, Loader2, PackageCheck, Printer, ReceiptText, Trash2 } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { adminNav } from "@/lib/nav";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { useAllOrders, useDeleteOrder, useOrderItems, useUpdateOrderStatus, type OrderRow } from "@/lib/api";
import { brl, formatDateTime, orderCategoryLabels, orderStatusLabels, orderStatuses, statusTone } from "@/lib/orders";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/pedidos")({ component: AdminPedidos });

function paymentLabel(status?: OrderRow["payment_status"]) { if (status === "approved") return "Pago"; if (status === "rejected") return "Pagamento recusado"; if (status === "cancelled") return "Pagamento cancelado"; return "Pagamento pendente"; }
function paymentTone(status?: OrderRow["payment_status"]): "default" | "secondary" | "outline" | "destructive" { if (status === "approved") return "default"; if (status === "rejected" || status === "cancelled") return "destructive"; return "outline"; }
function stayDetails(order: OrderRow) { try { const parsed = order.details ? JSON.parse(order.details) : {}; return { apartment_code: typeof parsed.apartment_code === "string" ? parsed.apartment_code : "", check_in: typeof parsed.check_in === "string" ? parsed.check_in : "", check_out: typeof parsed.check_out === "string" ? parsed.check_out : "", source: typeof parsed.source === "string" ? parsed.source : "" }; } catch { return { apartment_code: "", check_in: "", check_out: "", source: "" }; } }
function maintenanceDetails(order: OrderRow) { try { const parsed = order.details ? JSON.parse(order.details) : {}; return { solicitante: typeof parsed.solicitante === "string" ? parsed.solicitante : "", perfil: typeof parsed.perfil === "string" ? parsed.perfil : "", imovel: typeof parsed.imovel === "string" ? parsed.imovel : "", categoria: typeof parsed.categoria === "string" ? parsed.categoria : "", prioridade: typeof parsed.prioridade === "string" ? parsed.prioridade : "", descricao: typeof parsed.descricao === "string" ? parsed.descricao : "" }; } catch { return { solicitante: "", perfil: "", imovel: "", categoria: "", prioridade: "", descricao: "" }; } }
function displayDate(value: string) { if (!value) return "—"; const [year, month, day] = value.split("-"); return year && month && day ? `${day}/${month}/${year}` : value; }
function requesterLabel(order: OrderRow) { if (order.category === "manutencao") return maintenanceDetails(order).perfil || "Solicitante"; const source = stayDetails(order).source; if (source === "owner_market_cart" || source === "owner_cart") return "Proprietário"; if (source === "guest_market_cart" || source === "guest_cart") return "Hóspede"; return order.reservation_id ? "Hóspede" : "Solicitante"; }
function customerData(order: OrderRow) { const maintenance = order.category === "manutencao" ? maintenanceDetails(order) : null; return { name: order.customer_name?.trim() || order.owner_profile?.full_name?.trim() || maintenance?.solicitante?.trim() || "", phone: order.customer_phone?.trim() || order.owner_profile?.phone?.trim() || "", email: order.customer_email?.trim() || "" }; }

function AdminPedidos() {
  const { data: orders = [], isLoading } = useAllOrders();
  const updateStatus = useUpdateOrderStatus();
  const deleteOrder = useDeleteOrder();
  const [selected, setSelected] = useState<OrderRow | null>(null);
  const [chargingId, setChargingId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const { data: items = [], isLoading: itemsLoading } = useOrderItems(selected?.id);
  const imprimir = () => window.print();
  const excluirPedido = async (order: OrderRow) => {
    if (!window.confirm(`Excluir o pedido ${order.order_number}? Essa ação não pode ser desfeita.`)) return;
    setDeletingId(order.id);
    try { await deleteOrder.mutateAsync(order.id); toast.success(`Pedido ${order.order_number} excluído.`); if (selected?.id === order.id) setSelected(null); }
    catch (error) { toast.error("Não foi possível excluir o pedido.", { description: error instanceof Error ? error.message : undefined }); }
    finally { setDeletingId(null); }
  };
  const cobrarNovamente = async (order: OrderRow) => {
    if (order.payment_status === "approved") return;
    setChargingId(order.id);
    try { const { data, error } = await supabase.functions.invoke("mercado-pago-checkout", { body: { order_id: order.id } }); if (error) throw new Error(data?.error || error.message || "Não foi possível gerar a cobrança."); if (!data?.checkout_url) throw new Error(data?.error || "Não foi possível gerar a cobrança."); window.location.assign(data.checkout_url); }
    catch (error) { window.alert(`Não foi possível gerar a cobrança.\n\n${error instanceof Error ? error.message : "Tente novamente."}`); }
    finally { setChargingId(null); }
  };
  return <DashboardShell nav={adminNav} role="Administrador" logoutTo="/admin/login" title="Pedidos & Cobranças" subtitle="Acompanhe os pedidos, pagamentos e tenha o comprovante completo de cada venda.">
    <div className="mx-auto max-w-6xl space-y-6">
      <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader className="pb-2"><CardDescription>Pedidos recebidos</CardDescription><CardTitle className="text-2xl">{orders.filter((o) => !["concluido", "cancelado"].includes(o.status)).length}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Pagamentos pendentes</CardDescription><CardTitle className="text-2xl">{orders.filter((o) => o.payment_status !== "approved" && o.status !== "cancelado").length}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Pagamentos aprovados</CardDescription><CardTitle className="text-2xl">{orders.filter((o) => o.payment_status === "approved").length}</CardTitle></CardHeader></Card></div>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><PackageCheck className="h-5 w-5 text-primary" /> Todos os pedidos</CardTitle><CardDescription>Abra um pedido para visualizar a nota/comprovante completo, incluindo solicitante, dados de cobrança, hospedagem e itens.</CardDescription></CardHeader><CardContent>{isLoading ? <p className="py-10 text-center text-sm text-muted-foreground">Carregando pedidos...</p> : orders.length === 0 ? <div className="py-12 text-center"><ReceiptText className="mx-auto mb-3 h-10 w-10 text-muted-foreground" /><p className="font-medium">Nenhum pedido registrado.</p></div> : <div className="space-y-3">{orders.map((order) => { const stay = stayDetails(order); const maintenance = order.category === "manutencao" ? maintenanceDetails(order) : null; const customer = customerData(order); const apartment = order.apartments?.code || stay.apartment_code || maintenance?.imovel; return <div key={order.id} className="flex flex-col gap-4 rounded-xl border p-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-bold text-primary">{order.order_number}</span><Badge variant={statusTone(order.status)}>{orderStatusLabels[order.status]}</Badge><Badge variant={paymentTone(order.payment_status)}>{paymentLabel(order.payment_status)}</Badge><Badge variant="outline">{requesterLabel(order)}</Badge>{apartment && <Badge variant="outline">Apto {apartment}</Badge>}</div><p className="mt-2 font-medium">{customer.name || "Solicitante não informado"}</p><p className="text-xs text-muted-foreground">{orderCategoryLabels[order.category]} · {formatDateTime(order.created_at)} · {brl(Number(order.total))}{stay.check_in && stay.check_out ? ` · Estadia ${displayDate(stay.check_in)} → ${displayDate(stay.check_out)}` : ""}{maintenance?.descricao ? ` · ${maintenance.descricao}` : ""}</p></div><div className="flex items-center gap-2"><Select value={order.status} onValueChange={(value) => updateStatus.mutate({ id: order.id, status: value as OrderRow["status"] })}><SelectTrigger className="w-[165px]"><SelectValue /></SelectTrigger><SelectContent>{orderStatuses.map((status) => <SelectItem key={status} value={status}>{orderStatusLabels[status]}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={() => setSelected(order)} className="gap-2"><Eye className="h-4 w-4" /> Ver pedido</Button><Button variant="outline" size="icon" onClick={() => void excluirPedido(order)} disabled={deletingId === order.id} aria-label={`Excluir pedido ${order.order_number}`}>{deletingId === order.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4 text-destructive" />}</Button></div></div>; })}</div>}</CardContent></Card>
    </div>
    <Dialog open={!!selected} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">{selected && (() => { const stay = stayDetails(selected); const maintenance = selected.category === "manutencao" ? maintenanceDetails(selected) : null; const customer = customerData(selected); const requester = requesterLabel(selected); return <div id="order-receipt" className="space-y-5"><DialogHeader><div className="flex items-start justify-between gap-3"><div><DialogTitle className="text-xl">Nota do pedido {selected.order_number}</DialogTitle><p className="mt-1 text-sm text-muted-foreground">Comprovante operacional da solicitação</p></div><Button variant="outline" size="sm" onClick={imprimir} className="print:hidden"><Printer className="mr-2 h-4 w-4" /> Imprimir</Button></div></DialogHeader>
      {maintenance ? <div className="grid gap-3 rounded-lg border bg-muted/20 p-4 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Solicitante</p><p className="font-medium">{customer.name || "—"} <span className="text-xs text-muted-foreground">({requester})</span></p></div><div><p className="text-xs text-muted-foreground">Imóvel</p><p className="font-medium">{selected.apartments?.code || maintenance.imovel || "—"}</p></div><div><p className="text-xs text-muted-foreground">Categoria do problema</p><p className="font-medium">{maintenance.categoria || "—"}</p></div><div><p className="text-xs text-muted-foreground">Prioridade</p><p className="font-medium capitalize">{maintenance.prioridade || "—"}</p></div><div className="sm:col-span-2"><p className="text-xs text-muted-foreground">Descrição do problema</p><p className="font-medium">{maintenance.descricao || "Sem descrição informada."}</p></div></div> : <div className="grid gap-3 rounded-lg border bg-muted/20 p-4 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Solicitante</p><p className="font-medium">{requester}</p></div><div><p className="text-xs text-muted-foreground">Nome</p><p className="font-medium">{customer.name || "—"}</p></div><div><p className="text-xs text-muted-foreground">Apartamento</p><p className="font-medium">{selected.apartments?.code || stay.apartment_code || "—"}</p></div><div><p className="text-xs text-muted-foreground">Check-in</p><p className="font-medium">{displayDate(stay.check_in)}</p></div><div><p className="text-xs text-muted-foreground">Check-out</p><p className="font-medium">{displayDate(stay.check_out)}</p></div><div><p className="text-xs text-muted-foreground">CPF</p><p className="font-medium">{selected.customer_cpf || "—"}</p></div><div><p className="text-xs text-muted-foreground">Telefone</p><p className="font-medium">{customer.phone || "—"}</p></div><div className="sm:col-span-2"><p className="text-xs text-muted-foreground">E-mail</p><p className="font-medium break-all">{customer.email || "—"}</p></div></div>}
      {!maintenance && <div className="rounded-lg border"><div className="border-b p-4"><p className="font-semibold">Itens do pedido</p></div>{itemsLoading ? <p className="p-4 text-sm text-muted-foreground">Carregando itens...</p> : items.length === 0 ? <p className="p-4 text-sm text-muted-foreground">Nenhum item detalhado registrado.</p> : <div className="divide-y">{items.map((item) => <div key={item.id} className="p-4"><div className="flex justify-between gap-4"><div><p className="font-medium">{item.quantity} × {item.name}</p>{item.observation && <p className="mt-1 text-sm text-muted-foreground"><strong>Observação:</strong> {item.observation}</p>}</div><p className="font-medium">{brl(Number(item.unit_price) * item.quantity)}</p></div></div>)}</div>}</div>}
      <div className="grid gap-3 rounded-lg border p-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Categoria</p><p className="font-medium">{orderCategoryLabels[selected.category]}</p></div><div><p className="text-xs text-muted-foreground">Status</p><p className="font-medium">{orderStatusLabels[selected.status]}</p></div><div><p className="text-xs text-muted-foreground">Pagamento</p><p className="font-medium">{paymentLabel(selected.payment_status)}</p></div></div>
      <div className="flex items-center justify-between border-t pt-4"><span className="text-lg font-semibold">Total</span><strong className="font-serif text-2xl">{brl(Number(selected.total))}</strong></div>
      {selected.payment_status !== "approved" && <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">O pedido está registrado mesmo sem pagamento aprovado. Isso permite conferência e nova cobrança posteriormente.</div>}
      <div className="flex justify-between print:hidden"><Button variant="outline" onClick={() => void excluirPedido(selected)} disabled={deletingId === selected.id} className="gap-2 text-destructive hover:text-destructive">{deletingId === selected.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4" />} Excluir pedido</Button>{selected.payment_status !== "approved" && selected.category !== "manutencao" && <Button onClick={() => cobrarNovamente(selected)} disabled={chargingId === selected.id} className="gap-2">{chargingId === selected.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <ExternalLink className="h-4 w-4" />}{chargingId === selected.id ? "Gerando cobrança..." : "Cobrar novamente"}</Button>}</div><p className="text-center text-xs text-muted-foreground">Pedido criado em {formatDateTime(selected.created_at)} · Este documento é um comprovante do pedido, não uma NF-e fiscal.</p>
    </div>; })()}</DialogContent></Dialog>
  </DashboardShell>;
}
