/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminChamadosRouteImport } from './routes/admin.chamados'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminImoveisRouteImport } from './routes/admin.imoveis'
import { Route as AdminKitsRouteImport } from './routes/admin.kits'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMercadoRouteImport } from './routes/admin.mercado'
import { Route as AdminParceriasRouteImport } from './routes/admin.parcerias'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPrecosRouteImport } from './routes/admin.precos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as HospedeCarrinhoRouteImport } from './routes/hospede.carrinho'
import { Route as HospedeDashboardRouteImport } from './routes/hospede.dashboard'
import { Route as HospedeHistoricoRouteImport } from './routes/hospede.historico'
import { Route as HospedeKitsRouteImport } from './routes/hospede.kits'
import { Route as HospedeLimpezaRouteImport } from './routes/hospede.limpeza'
import { Route as HospedeLoginRouteImport } from './routes/hospede.login'
import { Route as HospedeMercadoRouteImport } from './routes/hospede.mercado'
import { Route as HospedeOrganizacaoRouteImport } from './routes/hospede.organizacao'
import { Route as HospedeServicosRouteImport } from './routes/hospede.servicos'
import { Route as HospedeVincularRouteImport } from './routes/hospede.vincular'
import { Route as ProprietarioApartamentosRouteImport } from './routes/proprietario.apartamentos'
import { Route as ProprietarioCarrinhoRouteImport } from './routes/proprietario.carrinho'
import { Route as ProprietarioDashboardRouteImport } from './routes/proprietario.dashboard'
import { Route as ProprietarioKitsRouteImport } from './routes/proprietario.kits'
import { Route as ProprietarioLoginRouteImport } from './routes/proprietario.login'
import { Route as ProprietarioManutencaoRouteImport } from './routes/proprietario.manutencao'
import { Route as ProprietarioMercadoRouteImport } from './routes/proprietario.mercado'
import { Route as ProprietarioParceriasRouteImport } from './routes/proprietario.parcerias'
import { Route as ProprietarioPedidosRouteImport } from './routes/proprietario.pedidos'
import { Route as ProprietarioRelatoriosRouteImport } from './routes/proprietario.relatorios'
import { Route as ProprietarioServicosRouteImport } from './routes/proprietario.servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChamadosRoute = AdminChamadosRouteImport.update({
  id: '/admin/chamados',
  path: '/admin/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImoveisRoute = AdminImoveisRouteImport.update({
  id: '/admin/imoveis',
  path: '/admin/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitsRoute = AdminKitsRouteImport.update({
  id: '/admin/kits',
  path: '/admin/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMercadoRoute = AdminMercadoRouteImport.update({
  id: '/admin/mercado',
  path: '/admin/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParceriasRoute = AdminParceriasRouteImport.update({
  id: '/admin/parcerias',
  path: '/admin/parcerias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/admin/precos',
  path: '/admin/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/admin/reservas',
  path: '/admin/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/admin/servicos',
  path: '/admin/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeCarrinhoRoute = HospedeCarrinhoRouteImport.update({
  id: '/hospede/carrinho',
  path: '/hospede/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeDashboardRoute = HospedeDashboardRouteImport.update({
  id: '/hospede/dashboard',
  path: '/hospede/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeHistoricoRoute = HospedeHistoricoRouteImport.update({
  id: '/hospede/historico',
  path: '/hospede/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeKitsRoute = HospedeKitsRouteImport.update({
  id: '/hospede/kits',
  path: '/hospede/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeLimpezaRoute = HospedeLimpezaRouteImport.update({
  id: '/hospede/limpeza',
  path: '/hospede/limpeza',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeLoginRoute = HospedeLoginRouteImport.update({
  id: '/hospede/login',
  path: '/hospede/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeMercadoRoute = HospedeMercadoRouteImport.update({
  id: '/hospede/mercado',
  path: '/hospede/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeOrganizacaoRoute = HospedeOrganizacaoRouteImport.update({
  id: '/hospede/organizacao',
  path: '/hospede/organizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeServicosRoute = HospedeServicosRouteImport.update({
  id: '/hospede/servicos',
  path: '/hospede/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedeVincularRoute = HospedeVincularRouteImport.update({
  id: '/hospede/vincular',
  path: '/hospede/vincular',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioApartamentosRoute =
  ProprietarioApartamentosRouteImport.update({
    id: '/proprietario/apartamentos',
    path: '/proprietario/apartamentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProprietarioCarrinhoRoute = ProprietarioCarrinhoRouteImport.update({
  id: '/proprietario/carrinho',
  path: '/proprietario/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioDashboardRoute = ProprietarioDashboardRouteImport.update({
  id: '/proprietario/dashboard',
  path: '/proprietario/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioKitsRoute = ProprietarioKitsRouteImport.update({
  id: '/proprietario/kits',
  path: '/proprietario/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioLoginRoute = ProprietarioLoginRouteImport.update({
  id: '/proprietario/login',
  path: '/proprietario/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioManutencaoRoute = ProprietarioManutencaoRouteImport.update({
  id: '/proprietario/manutencao',
  path: '/proprietario/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioMercadoRoute = ProprietarioMercadoRouteImport.update({
  id: '/proprietario/mercado',
  path: '/proprietario/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioParceriasRoute = ProprietarioParceriasRouteImport.update({
  id: '/proprietario/parcerias',
  path: '/proprietario/parcerias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioPedidosRoute = ProprietarioPedidosRouteImport.update({
  id: '/proprietario/pedidos',
  path: '/proprietario/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioRelatoriosRoute = ProprietarioRelatoriosRouteImport.update({
  id: '/proprietario/relatorios',
  path: '/proprietario/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioServicosRoute = ProprietarioServicosRouteImport.update({
  id: '/proprietario/servicos',
  path: '/proprietario/servicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/admin/chamados': typeof AdminChamadosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/imoveis': typeof AdminImoveisRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mercado': typeof AdminMercadoRoute
  '/admin/parcerias': typeof AdminParceriasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/hospede/carrinho': typeof HospedeCarrinhoRoute
  '/hospede/dashboard': typeof HospedeDashboardRoute
  '/hospede/historico': typeof HospedeHistoricoRoute
  '/hospede/kits': typeof HospedeKitsRoute
  '/hospede/limpeza': typeof HospedeLimpezaRoute
  '/hospede/login': typeof HospedeLoginRoute
  '/hospede/mercado': typeof HospedeMercadoRoute
  '/hospede/organizacao': typeof HospedeOrganizacaoRoute
  '/hospede/servicos': typeof HospedeServicosRoute
  '/hospede/vincular': typeof HospedeVincularRoute
  '/proprietario/apartamentos': typeof ProprietarioApartamentosRoute
  '/proprietario/carrinho': typeof ProprietarioCarrinhoRoute
  '/proprietario/dashboard': typeof ProprietarioDashboardRoute
  '/proprietario/kits': typeof ProprietarioKitsRoute
  '/proprietario/login': typeof ProprietarioLoginRoute
  '/proprietario/manutencao': typeof ProprietarioManutencaoRoute
  '/proprietario/mercado': typeof ProprietarioMercadoRoute
  '/proprietario/parcerias': typeof ProprietarioParceriasRoute
  '/proprietario/pedidos': typeof ProprietarioPedidosRoute
  '/proprietario/relatorios': typeof ProprietarioRelatoriosRoute
  '/proprietario/servicos': typeof ProprietarioServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/admin/chamados': typeof AdminChamadosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/imoveis': typeof AdminImoveisRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mercado': typeof AdminMercadoRoute
  '/admin/parcerias': typeof AdminParceriasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/hospede/carrinho': typeof HospedeCarrinhoRoute
  '/hospede/dashboard': typeof HospedeDashboardRoute
  '/hospede/historico': typeof HospedeHistoricoRoute
  '/hospede/kits': typeof HospedeKitsRoute
  '/hospede/limpeza': typeof HospedeLimpezaRoute
  '/hospede/login': typeof HospedeLoginRoute
  '/hospede/mercado': typeof HospedeMercadoRoute
  '/hospede/organizacao': typeof HospedeOrganizacaoRoute
  '/hospede/servicos': typeof HospedeServicosRoute
  '/hospede/vincular': typeof HospedeVincularRoute
  '/proprietario/apartamentos': typeof ProprietarioApartamentosRoute
  '/proprietario/carrinho': typeof ProprietarioCarrinhoRoute
  '/proprietario/dashboard': typeof ProprietarioDashboardRoute
  '/proprietario/kits': typeof ProprietarioKitsRoute
  '/proprietario/login': typeof ProprietarioLoginRoute
  '/proprietario/manutencao': typeof ProprietarioManutencaoRoute
  '/proprietario/mercado': typeof ProprietarioMercadoRoute
  '/proprietario/parcerias': typeof ProprietarioParceriasRoute
  '/proprietario/pedidos': typeof ProprietarioPedidosRoute
  '/proprietario/relatorios': typeof ProprietarioRelatoriosRoute
  '/proprietario/servicos': typeof ProprietarioServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/admin/chamados': typeof AdminChamadosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/imoveis': typeof AdminImoveisRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mercado': typeof AdminMercadoRoute
  '/admin/parcerias': typeof AdminParceriasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/hospede/carrinho': typeof HospedeCarrinhoRoute
  '/hospede/dashboard': typeof HospedeDashboardRoute
  '/hospede/historico': typeof HospedeHistoricoRoute
  '/hospede/kits': typeof HospedeKitsRoute
  '/hospede/limpeza': typeof HospedeLimpezaRoute
  '/hospede/login': typeof HospedeLoginRoute
  '/hospede/mercado': typeof HospedeMercadoRoute
  '/hospede/organizacao': typeof HospedeOrganizacaoRoute
  '/hospede/servicos': typeof HospedeServicosRoute
  '/hospede/vincular': typeof HospedeVincularRoute
  '/proprietario/apartamentos': typeof ProprietarioApartamentosRoute
  '/proprietario/carrinho': typeof ProprietarioCarrinhoRoute
  '/proprietario/dashboard': typeof ProprietarioDashboardRoute
  '/proprietario/kits': typeof ProprietarioKitsRoute
  '/proprietario/login': typeof ProprietarioLoginRoute
  '/proprietario/manutencao': typeof ProprietarioManutencaoRoute
  '/proprietario/mercado': typeof ProprietarioMercadoRoute
  '/proprietario/parcerias': typeof ProprietarioParceriasRoute
  '/proprietario/pedidos': typeof ProprietarioPedidosRoute
  '/proprietario/relatorios': typeof ProprietarioRelatoriosRoute
  '/proprietario/servicos': typeof ProprietarioServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/admin/chamados'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/imoveis'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/mercado'
    | '/admin/parcerias'
    | '/admin/pedidos'
    | '/admin/precos'
    | '/admin/relatorios'
    | '/admin/reservas'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/hospede/carrinho'
    | '/hospede/dashboard'
    | '/hospede/historico'
    | '/hospede/kits'
    | '/hospede/limpeza'
    | '/hospede/login'
    | '/hospede/mercado'
    | '/hospede/organizacao'
    | '/hospede/servicos'
    | '/hospede/vincular'
    | '/proprietario/apartamentos'
    | '/proprietario/carrinho'
    | '/proprietario/dashboard'
    | '/proprietario/kits'
    | '/proprietario/login'
    | '/proprietario/manutencao'
    | '/proprietario/mercado'
    | '/proprietario/parcerias'
    | '/proprietario/pedidos'
    | '/proprietario/relatorios'
    | '/proprietario/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/admin/chamados'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/imoveis'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/mercado'
    | '/admin/parcerias'
    | '/admin/pedidos'
    | '/admin/precos'
    | '/admin/relatorios'
    | '/admin/reservas'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/hospede/carrinho'
    | '/hospede/dashboard'
    | '/hospede/historico'
    | '/hospede/kits'
    | '/hospede/limpeza'
    | '/hospede/login'
    | '/hospede/mercado'
    | '/hospede/organizacao'
    | '/hospede/servicos'
    | '/hospede/vincular'
    | '/proprietario/apartamentos'
    | '/proprietario/carrinho'
    | '/proprietario/dashboard'
    | '/proprietario/kits'
    | '/proprietario/login'
    | '/proprietario/manutencao'
    | '/proprietario/mercado'
    | '/proprietario/parcerias'
    | '/proprietario/pedidos'
    | '/proprietario/relatorios'
    | '/proprietario/servicos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/admin/chamados'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/imoveis'
    | '/admin/kits'
    | '/admin/login'
    | '/admin/mercado'
    | '/admin/parcerias'
    | '/admin/pedidos'
    | '/admin/precos'
    | '/admin/relatorios'
    | '/admin/reservas'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/hospede/carrinho'
    | '/hospede/dashboard'
    | '/hospede/historico'
    | '/hospede/kits'
    | '/hospede/limpeza'
    | '/hospede/login'
    | '/hospede/mercado'
    | '/hospede/organizacao'
    | '/hospede/servicos'
    | '/hospede/vincular'
    | '/proprietario/apartamentos'
    | '/proprietario/carrinho'
    | '/proprietario/dashboard'
    | '/proprietario/kits'
    | '/proprietario/login'
    | '/proprietario/manutencao'
    | '/proprietario/mercado'
    | '/proprietario/parcerias'
    | '/proprietario/pedidos'
    | '/proprietario/relatorios'
    | '/proprietario/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  AdminChamadosRoute: typeof AdminChamadosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminImoveisRoute: typeof AdminImoveisRoute
  AdminKitsRoute: typeof AdminKitsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMercadoRoute: typeof AdminMercadoRoute
  AdminParceriasRoute: typeof AdminParceriasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  HospedeCarrinhoRoute: typeof HospedeCarrinhoRoute
  HospedeDashboardRoute: typeof HospedeDashboardRoute
  HospedeHistoricoRoute: typeof HospedeHistoricoRoute
  HospedeKitsRoute: typeof HospedeKitsRoute
  HospedeLimpezaRoute: typeof HospedeLimpezaRoute
  HospedeLoginRoute: typeof HospedeLoginRoute
  HospedeMercadoRoute: typeof HospedeMercadoRoute
  HospedeOrganizacaoRoute: typeof HospedeOrganizacaoRoute
  HospedeServicosRoute: typeof HospedeServicosRoute
  HospedeVincularRoute: typeof HospedeVincularRoute
  ProprietarioApartamentosRoute: typeof ProprietarioApartamentosRoute
  ProprietarioCarrinhoRoute: typeof ProprietarioCarrinhoRoute
  ProprietarioDashboardRoute: typeof ProprietarioDashboardRoute
  ProprietarioKitsRoute: typeof ProprietarioKitsRoute
  ProprietarioLoginRoute: typeof ProprietarioLoginRoute
  ProprietarioManutencaoRoute: typeof ProprietarioManutencaoRoute
  ProprietarioMercadoRoute: typeof ProprietarioMercadoRoute
  ProprietarioParceriasRoute: typeof ProprietarioParceriasRoute
  ProprietarioPedidosRoute: typeof ProprietarioPedidosRoute
  ProprietarioRelatoriosRoute: typeof ProprietarioRelatoriosRoute
  ProprietarioServicosRoute: typeof ProprietarioServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chamados': {
      id: '/admin/chamados'
      path: '/admin/chamados'
      fullPath: '/admin/chamados'
      preLoaderRoute: typeof AdminChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/imoveis': {
      id: '/admin/imoveis'
      path: '/admin/imoveis'
      fullPath: '/admin/imoveis'
      preLoaderRoute: typeof AdminImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kits': {
      id: '/admin/kits'
      path: '/admin/kits'
      fullPath: '/admin/kits'
      preLoaderRoute: typeof AdminKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mercado': {
      id: '/admin/mercado'
      path: '/admin/mercado'
      fullPath: '/admin/mercado'
      preLoaderRoute: typeof AdminMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parcerias': {
      id: '/admin/parcerias'
      path: '/admin/parcerias'
      fullPath: '/admin/parcerias'
      preLoaderRoute: typeof AdminParceriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/precos': {
      id: '/admin/precos'
      path: '/admin/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/admin/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/admin/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/carrinho': {
      id: '/hospede/carrinho'
      path: '/hospede/carrinho'
      fullPath: '/hospede/carrinho'
      preLoaderRoute: typeof HospedeCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/dashboard': {
      id: '/hospede/dashboard'
      path: '/hospede/dashboard'
      fullPath: '/hospede/dashboard'
      preLoaderRoute: typeof HospedeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/historico': {
      id: '/hospede/historico'
      path: '/hospede/historico'
      fullPath: '/hospede/historico'
      preLoaderRoute: typeof HospedeHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/kits': {
      id: '/hospede/kits'
      path: '/hospede/kits'
      fullPath: '/hospede/kits'
      preLoaderRoute: typeof HospedeKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/limpeza': {
      id: '/hospede/limpeza'
      path: '/hospede/limpeza'
      fullPath: '/hospede/limpeza'
      preLoaderRoute: typeof HospedeLimpezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/login': {
      id: '/hospede/login'
      path: '/hospede/login'
      fullPath: '/hospede/login'
      preLoaderRoute: typeof HospedeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/mercado': {
      id: '/hospede/mercado'
      path: '/hospede/mercado'
      fullPath: '/hospede/mercado'
      preLoaderRoute: typeof HospedeMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/organizacao': {
      id: '/hospede/organizacao'
      path: '/hospede/organizacao'
      fullPath: '/hospede/organizacao'
      preLoaderRoute: typeof HospedeOrganizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/servicos': {
      id: '/hospede/servicos'
      path: '/hospede/servicos'
      fullPath: '/hospede/servicos'
      preLoaderRoute: typeof HospedeServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospede/vincular': {
      id: '/hospede/vincular'
      path: '/hospede/vincular'
      fullPath: '/hospede/vincular'
      preLoaderRoute: typeof HospedeVincularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/apartamentos': {
      id: '/proprietario/apartamentos'
      path: '/proprietario/apartamentos'
      fullPath: '/proprietario/apartamentos'
      preLoaderRoute: typeof ProprietarioApartamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/carrinho': {
      id: '/proprietario/carrinho'
      path: '/proprietario/carrinho'
      fullPath: '/proprietario/carrinho'
      preLoaderRoute: typeof ProprietarioCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/dashboard': {
      id: '/proprietario/dashboard'
      path: '/proprietario/dashboard'
      fullPath: '/proprietario/dashboard'
      preLoaderRoute: typeof ProprietarioDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/kits': {
      id: '/proprietario/kits'
      path: '/proprietario/kits'
      fullPath: '/proprietario/kits'
      preLoaderRoute: typeof ProprietarioKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/login': {
      id: '/proprietario/login'
      path: '/proprietario/login'
      fullPath: '/proprietario/login'
      preLoaderRoute: typeof ProprietarioLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/manutencao': {
      id: '/proprietario/manutencao'
      path: '/proprietario/manutencao'
      fullPath: '/proprietario/manutencao'
      preLoaderRoute: typeof ProprietarioManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/mercado': {
      id: '/proprietario/mercado'
      path: '/proprietario/mercado'
      fullPath: '/proprietario/mercado'
      preLoaderRoute: typeof ProprietarioMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/parcerias': {
      id: '/proprietario/parcerias'
      path: '/proprietario/parcerias'
      fullPath: '/proprietario/parcerias'
      preLoaderRoute: typeof ProprietarioParceriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/pedidos': {
      id: '/proprietario/pedidos'
      path: '/proprietario/pedidos'
      fullPath: '/proprietario/pedidos'
      preLoaderRoute: typeof ProprietarioPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/relatorios': {
      id: '/proprietario/relatorios'
      path: '/proprietario/relatorios'
      fullPath: '/proprietario/relatorios'
      preLoaderRoute: typeof ProprietarioRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/servicos': {
      id: '/proprietario/servicos'
      path: '/proprietario/servicos'
      fullPath: '/proprietario/servicos'
      preLoaderRoute: typeof ProprietarioServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  AdminChamadosRoute: AdminChamadosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminImoveisRoute: AdminImoveisRoute,
  AdminKitsRoute: AdminKitsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMercadoRoute: AdminMercadoRoute,
  AdminParceriasRoute: AdminParceriasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  HospedeCarrinhoRoute: HospedeCarrinhoRoute,
  HospedeDashboardRoute: HospedeDashboardRoute,
  HospedeHistoricoRoute: HospedeHistoricoRoute,
  HospedeKitsRoute: HospedeKitsRoute,
  HospedeLimpezaRoute: HospedeLimpezaRoute,
  HospedeLoginRoute: HospedeLoginRoute,
  HospedeMercadoRoute: HospedeMercadoRoute,
  HospedeOrganizacaoRoute: HospedeOrganizacaoRoute,
  HospedeServicosRoute: HospedeServicosRoute,
  HospedeVincularRoute: HospedeVincularRoute,
  ProprietarioApartamentosRoute: ProprietarioApartamentosRoute,
  ProprietarioCarrinhoRoute: ProprietarioCarrinhoRoute,
  ProprietarioDashboardRoute: ProprietarioDashboardRoute,
  ProprietarioKitsRoute: ProprietarioKitsRoute,
  ProprietarioLoginRoute: ProprietarioLoginRoute,
  ProprietarioManutencaoRoute: ProprietarioManutencaoRoute,
  ProprietarioMercadoRoute: ProprietarioMercadoRoute,
  ProprietarioParceriasRoute: ProprietarioParceriasRoute,
  ProprietarioPedidosRoute: ProprietarioPedidosRoute,
  ProprietarioRelatoriosRoute: ProprietarioRelatoriosRoute,
  ProprietarioServicosRoute: ProprietarioServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
